# must specify
model: k_means.model.TrainModel
iterator: k_means.model.Trainer
dataset: k_means.data.Dataset_MNIST

batch_size: 1024
num_steps: 501
lr : 1.0e-4  # yaml needs 1.0 for exponential notation
lr_decay_begin : 100 # TODO remove these in future versions
lr_decay_end : 1001  # TODO remove these in future versions


# options
spatial_size: 28
log_freq : 10
ckpt_freq : 300
is_train: True
n_processes : 1

# cd edflow/examples
# run with edflow -t mnist_tf/train.yaml -n mnist_tf -e mnist_tf/validation.yaml
# edflow -e mnist_tf/validation.yaml -b mnist_tf/train.yaml -c logs/2019-06-05T09:17:00_mnist_tf/train/checkpoints/model.ckpt-200 -n test # evaluate into test directory
# edflow -e mnist_tf/validation.yaml -b mnist_tf/train.yaml -c logs/2019-06-05T09:17:00_mnist_tf/train/checkpoints/model.ckpt-200 -p logs/2019-06-05T09:17:00_mnist_tf # evalute into project eval folder
# edflow -e mnist_tf/validation.yaml -b mnist_tf/train.yaml -p logs/2019-06-05T09:17:00_mnist_tf # evaluate into project eval folder with last checkpoint


# logging options
log_images_to_tensorboard: True


k : 25 # The number of clusters
num_classes : 10 # The 10 digits
num_features : 784 # Each image is 28x28 pixels
mini_batch_steps_per_iteration: 10