model: eval_hook.model.CNN
iterator: eval_hook.model.Iterator

dataset: eval_hook.dataset.Dataset_MNIST

code_root: null


batch_size: 30
spatial_size: 28

drop_prob: 0.0

hook_freq: 1
log_freq: 1000
ckpt_freq: 1000
mode: "eval"
