#!/usr/bin/env python3

import os
import shutil


def create_edflow_project(project_name, replace: bool=False):
    """
    Creates a fresh new project directory with all the needed skeletons which are edflow compatible.

    Parameters
    ----------
    project_name (str) : Name of your new project. This will also be the name of the parent folder.
    replace (bool) : If a old project shall be replaced in case it exists.

    Returns
    -------

    """
    if os.path.exists(project_name) and not replace:
        raise FileExistsError("Directory already exists. Provide a different name for the project "
                              "OR set replace to True")
    shutil.copytree()