dataset: python_only.simple_python_example.SomeData
iterator: python_only.simple_python_example.PyRunner
model: python_only.simple_python_example.Model

# Iterator
batch_size: 5
num_steps: 2500

# Model
mem_size: -1
queue_type: "fifo"

# Data
example_names: ["a", "b", "c"]
num_example: 1000
