model: mnist_pytorch.model.CNN
iterator: mnist_pytorch.model.Iterator

dataset: mnist_pytorch.dataset.Dataset_MNIST


batch_size: 30
spatial_size: 28

num_steps: &ns 1000
lr: &lr 2.0e-5  # Default 2.0e-4
drop_prob: 0.0

lr_decay_pars:
  start: [4000, *lr]
  stop: [*ns, 1.0e-8]

hook_freq: 1
log_freq: 1000
ckpt_freq: 1000
mode: 'train'